name: Build, Push, and Deploy Docker Image

on:
  push:
    branches:
      - main


env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  DOCKER_IMAGE_NAME: pentagol
  DOCKER_IMAGE_TAG: latest
  SERVER_HOST: 18.196.64.112
  SERVER_USERNAME: ubuntu
  SSH_PRIVATE_KEY: AAAAB3NzaC1yc2EAAAADAQABAAABgQDJOOydhZ/+tQe6dp53/uewJoydjO/QGHmJFMBRjcN4PgIpb2KPmOK/7UODF1zQnWH5NojUhe8kT+QuXzu9zAtupJEJx4+LBlL1IAUNnLfqh1R6VJlzJI5gf2twrX8RKXkvyyWGayAihdUist6zc6HE6m1h2L4qbkQMMnfjKzRKJ5I+3Fwl2VcMDBErABf9AJyLOXQUGzW7xz4JkXrVlFP+WJVEpriIf+V7UImDD/72kPtpzLEAqEx73zbHt+/aoirEZsgRDGKXXMIgngXPcmepa3xX0F/i42c6RGVP/z63gpU87AFfFK3r73QlHP/MhRstWmmviDX6o1p877nnjY1nqItN8gUBdqaX+AiaDkSGYcf7uxMJCQbzP7t+Ad4IGYtU8oxpSWZ4pCpU72ShCEGSH7iscqQenG91GNvkZIaaO/HvhiGfK6aVGOQlpo9iWYTV85YVCvMBuB1WWtqYx0GR87qruhH2DmRNIYpUUQ86osRICt44Zq5EScEdxJ/tQIs= ubuntu@ip-172-26-4-99
  DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
  DATABASE_USER: ${{ secrets.DATABASE_USER }}
  DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}


jobs:
  build_push_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ env.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push Docker image
        run: |
          docker buildx create --use --name mybuilder
          docker buildx build --platform linux/amd64,linux/arm64 --push -t $DOCKER_USERNAME/$DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG .

      - name: Deploy Docker image to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.SERVER_HOST }}
          username: ${{ env.SERVER_USERNAME }}
          key: ${{ env.SSH_PRIVATE_KEY }}
          script: |
            docker stop blog || true
            docker rm blog || true
            docker image rm ${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_IMAGE_TAG }} || true
            docker run -d --name blog -e POSTGRES_HOST=${{ env.DATABASE_HOST }} -e POSTGRES_USER=${{ env.DATABASE_USER }} -e POSTGRES_PASSWORD=${{ env.DATABASE_PASSWORD }} -p 8000:8000 ${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_IMAGE_TAG }}